### ISSUE TITLE
RIP R2B2

### ISSUE THREAD

**Issue by jnormile** [term-world/yard-solved#10]
## Describe the bug

When an erroneous calculation is performed with the `Luumba` and an incorrect amount of surface area is passed as the solution, the narrator mentions `R2B2`, who needs to be put to rest at this point. (Long live the `Luumba`)

**Comment by dluman** [comment]
You'll be glad to know, @jnormile, that the Luumba is still named R2B2, as the narration now reads:

```yaml
0:
  0: 
    - It appears that R2B2 the Luumba doesn't agree with your calculations.
    - Rather than having an unproductive dispute with a robot,
    - check your calculations.
```
